config/routes.rb
Bpr::Application.routes.draw do
  resources :restrooms do
    resources :reviews
  end
  match 'search', to: 'restrooms#search', via: 'get' 
  match '/add', to: 'restrooms#create', via: 'post'
  root 'static_pages#home' 
  match 'contact', to: 'static_pages#contact', via: 'get' 
  match 'about', to: 'static_pages#about', via: 'get'
  
  resources :users 
  match 'signup', to: 'users#new', via: 'get' 
  
  resources :sessions, only: [:new, :create, :destroy] 
  match 'signin', to: 'sessions#new', via: 'get' 
  match 'signout', to: 'sessions#destroy', via: 'delete' 
  

  

end

app/models/restroom.rb
class Restroom < ActiveRecord::Base
  has_many :reviews, dependent: :destroy  	

  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true 
  validates :line1, presence: true, length: { maximum: 50 }
  validates :line2, length: { maximum: 50 }, allow_blank: true  
  validates :city, presence: true, length: { maximum: 50 } 
  validates :state, presence: true, length: { is: 2 }  
  validates :zip, presence: true, format: { with: /\A\d{5}(?:[-\s]\d{4})?\z/ } 
#  validates :query, presence: true   

  def self.search(params)
  #  if search
      where 'zip LIKE ?', "%#{params}%"  
   # else
    #  scoped 
   # end 
  end 

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restroom 
  validates :restroom_id, presence: true
  validates :content, presence: true
  validates :author, presence: true  
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase } 
  before_create :create_remember_token 

  validates :name, presence: true, length: { maximum: 50 } 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  			uniqueness: true 
  validates :password, length: { minimum: 6 } 
  has_secure_password  
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end 
  
  def User.encrypt(token) 
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  private
    
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper 
end

app/controllers/restrooms_controller.rb
class RestroomsController < ApplicationController
  before_action :signed_in_user, only: [:create, :new]  

  def new
    @restroom = Restroom.new 
  end
  
  def create
    @restroom = Restroom.new(restroom_params)
    if @restroom.save
     redirect_to @restroom
    else
      render 'new'
    end 
  end 
  
  def index
    @restrooms = Restroom.paginate(page: params[:page]) 
  end
  
  def show
    @restroom = Restroom.find(params[:id]) 
    @reviews = @restroom.reviews.paginate(page: params[:page]) 
    @new_review = @restroom.reviews.build if signed_in?  
  end
  
  def search
    @params = params[:search] 
     #add validations for search form 
    @restrooms = Restroom.search(params[:search])
  end 

  
  private
    
    def restroom_params
      params.require(:restroom).permit(:name, :line1, :line2, :city, :state, :zip)
      
    end

    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :signed_in_user
  
  def new
	@restroom = Restroom.find(params[:restroom_id]) 
	@review = @restroom.reviews.build
  end
  
  def create
  	@restroom = Restroom.find(params[:restroom_id]) 
    @review = @restroom.reviews.build(review_params) 
    @review.author = current_user.email
    if @review.save
      flash[:success] = "Review created" 
      redirect_to restroom_path(@restroom) 
    else
	  redirect_to new_restroom_review_path(@restroom)  
    end 
  end
  
  def destroy
  end
  
  private 
    
    def review_params
      params.require(:review).permit(:content, :restroom_id) 
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase) 
    if user && user.authenticate(params[:session][:password]) 
      sign_in user
      redirect_back_or user 
    else
      flash.now[:error] = 'Invalid email/password combination' 
      render 'new' 
    end
  end
  
  def destroy
    sign_out
    redirect_to root_url 
  end 
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id]) 
  end
  
  def new
    @user = User.new
  end 
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!" 
      redirect_to @user
    else
      render 'new'
    end 
  end

  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, 
      							   :password_confirmation) 
    end 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Boston Public Restrooms" 
    if page_title.empty?
      base_title 
    else
     " #{base_title} | #{page_title}" 
    end
  end 
  
end

app/helpers/restrooms_helper.rb
module RestroomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token)) 
    self.current_user = user
  end 
  
  def signed_in?
    !current_user.nil? 
  end
  
  def current_user=(user)
    @current_user = user 
  end
  
  def current_user 
    remember_token = User.encrypt(cookies[:remember_token]) 
    @current_user ||= User.find_by(remember_token: remember_token) 
  end 
  
  def sign_out 
    self.current_user = nil
    cookies.delete(:remember_token) 
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default) 
    session.delete(:return_to)
  end
  
  def store_location
    session[:return_to] = request.url 
  end

  def current_user?(user)
    user == current_user
  end  
  
  def signed_in_user
    unless signed_in?
	  store_location
	  redirect_to signin_url, notice: "Please sign in." unless signed_in? 
    end
  end 
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Home", root_path%></li>
	  <li><%= link_to "About", "#about-modal", "data-toggle" => "modal" %></li>
      <li><%= link_to "Contact", '#contact-modal', "data-toggle" => "modal" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
	<%=link_to "BPR", root_path, id: "logo" %>
	</nav>
	<nav>
	  <% if signed_in? %>
		<li id="fat-menu" class="dropdown">
		  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			My Account <b class="caret"></b>
		  </a>
		  <ul class="dropdown-menu">
			<li><%= link_to "Profile", current_user %></li>
			<li><%= link_to "Settings", '#' %></li>
			<li class="divider">fsafewafewafdsfdas</li>
			<li>
			  <%= link_to "Sign out", signout_path, method: "delete" %>
			</li>
		  </ul>
		</li>
	    <li><%= link_to "All Users", users_path %></li>
	  <% else %>
		<li><%= link_to "Sign in", signin_path %></li>
		<li><%= link_to "Sign Up", signup_path %></li> 
	  <% end %>
	  </ul> 
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
  	<%= render 'layouts/header' %> 
	  <div class="container"> 
	    <% flash.each do |key, value| %> 
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %> 
		<%= yield %>
	</div> 
	<%= render 'shared/about_modal' %> 
	<%= render 'shared/contact_modal' %> 
	<%= render 'layouts/footer' %> 
  </body>
</html>

app/views/restrooms/_display_restrooms.html.erb
<ul id="search_results">
  <% object.each do |r| %>
	<li>
	  <div class="restroom_name">
		<%= link_to r.name, restroom_path(r) %> 
	  </div>
	  <div class="restroom_info">
		<%= r.line1 %>  
		<%= r.city %>, 
		<%= r.state%>, 
		<%= r.zip %> 
	  </div>
	</li> 
  <% end %>
</ul>

app/views/restrooms/index.html.erb
<% provide(:title, 'All Restrooms') %> 

<h1> All Restrooms </h1> 

<%= will_paginate %> 

<%= render 'display_restrooms', object: @restrooms %> 

<%= will_paginate %> 

app/views/restrooms/new.html.erb
<% provide(:title, 'Add Restroom') %> 
<h1>Add Restroom</h1>

<div class="row">
  <div class="span9">
    <div class="row">
      <%= form_for(@restroom) do |f|%>
      <%= render 'shared/error_messages', object: @restroom %>
      <div class="span4">
		 <%= f.label :Name%>
		 <%= f.text_field :name, placeholder: "Name of Restroom" %>
	
		 <%= f.label :Address%>
		 <%= f.text_field :line1, placeholder: "Restroom Address"%>
	
		 <%= f.text_field :line2, placeholder: "Second Line (Optional)"%>
 	  </div>
 	  <div class="span4">	  
		 <%= f.label :City%>
		 <%= f.text_field :city, placeholder: "City"%>
	
		 <%= f.label :State%>
		 <%= f.text_field :state, placeholder: "State Abbreviation"%>
	
		 <%= f.label :zip%>
		 <%= f.text_field :zip, placeholder: "Zip Code"%>
		 <%= f.submit "Add This Restroom"%>
		 <% end %>  
	  </div>
    </div> 
  </div>
</div>

app/views/restrooms/search.html.erb
<% provide(:title, 'Search Results') %> 

<h1>Restrooms near <%= @params %> </h1> 

<%= render 'display_restrooms', object: @restrooms %> 

app/views/restrooms/show.html.erb
<% provide(:title, @restroom.name) %> 
<h2> <%= @restroom.name %> </h2>
<p><%= @restroom.line1 %> <br /> 
<%= @restroom.city %>, <%= @restroom.state%> , <%= @restroom.zip %> </p> 
<% if @restroom.reviews.any? %> 
  <h4> Reviews: <%= @restroom.reviews.count %> </h4> 
  <ol class= "reviews"> 
    <%= render @reviews %> 
  </ol>
    <%= will_paginate @reviews %> 
<% end %> 

<%= link_to 'Add a Review', new_restroom_review_path(@restroom) %>

app/views/reviews/_review.html.erb
<ul class="single_review">
  <div id="review_auth">
    <li><%= link_to review.author, 
  			user_path(User.find_by email: review.author) %></li> 
  </div>
  <div id="review_content">
    <li><%= review.content %></li>
  </div> 
</ul> 

app/views/reviews/new.html.erb
<h3>Write a Review for <%= @restroom.name %></h3>
<%= render 'shared/error_messages', object: @review %> 
<%= form_for([@restroom, @review]) do |f| %>
  <div class="field"> 
    <%= f.text_area :content, placeholder: "Write Review Here" %> 
  </div> 
  <%= f.submit "Review", class: "btn btn-primary" %> 
<% end %> 

app/views/shared/_about_modal.html.erb
<!-- Modal -->
<div id="about-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">About BPR</h3>
    </div>
  <div class="modal-body">
    <p>Welcome to Boston Public Restrooms. Hopefully, you'll find this app helpful
       in discovering the nearest public restroom in Boston! </p>
    <h4>The Creator</h4> 
      <p>Cameron Jackson, a student at Tufts University (outside Boston), created this
      application. It is very much a work in progress, and the source code is available
      at http://github.com/cjacks0413/otis-bos. Feel free to contribute it you're interested!
      </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/shared/_contact_modal.html.erb
<!-- Modal -->
<div id="contact-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Contact</h3>
    </div>
  <div class="modal-body">
    <p></p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any?%>
  <div id="error_explanation">
    <div class="alert alert-error"> 
      The form contains <%= pluralize(object.errors.count, 'error') %> 
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %> 
      <li> <%= msg %></li>
    <% end %> 
    </ul>
  </div>
<% end %> 

app/views/shared/_review_form.html.erb
<%= form_for(@new_review) do |f| %> 
  <%= render 'shared/error_messages', object: f.object %> 
  <div class="field"> 
    <%= f.text_area :content, placeholder: "Write Review Here" %> 
  </div> 
  <%= f.submit "Review", class: "btn btn-primary" %> 
<% end %>

app/views/shared/_search_form.html.erb
<%= form_tag(search_path, method: :get) do %> 
  <%= text_field_tag :search, params[:search], placeholder: "Enter Zip" %>
  <%= submit_tag "Search" %> 
<% end %> 

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %> 
<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %> 
<h1>Contact</h1>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="span9">
	<h1>Welcome to Boston Public Restrooms!</h1>
	<div class="row">
	  <div class="span3">
			<h2>This is your guide to public restrooms in the Boston area. 
			Get reviews, maps, ratings, and more! </h2>
	  </div> 
	  <div class="span3 offset2">
		 <%= render 'shared/search_form'%>   
		 <h2><%= link_to "Add a restroom!", new_restroom_path %></h2>
		 <h2><%= link_to "All Restrooms", restrooms_path %></h2> 
      </div> 
	</div>	
  </div> 
  <div class="span6"> 
	 <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-inverse"%>
  </div>
</div> 
  

app/views/users/index.html.erb
<%= provide(:title, 'All Users') %>

<h1> All Users </h1> 

<%= will_paginate %> 

<% @users.each do |u| %> 
	<li>
	  <div class="restroom_name">
		<%= link_to u.name, user_path(u) %> 
	  </div>
	  <div class="restroom_info">
		<%= u.email %>  
	  </div>
	</li> 
  <% end %>
</ul>
<%= will_paginate %> 

app/views/users/new.html.erb
<%= provide(:title, 'Sign Up') %> 

<h1>Sign Up</h1>

<div class="row">
  <div class="span9">
    <div class="row">
      <%= form_for(@user) do |f|%>
      <%= render 'shared/error_messages', object: @user %> 
	<div class="span6"> 
		<%= f.label :Name%>
		<%= f.text_field :name, placeholder: "First and Last Name" %>
 
		<%= f.label :Email%>
		<%= f.text_field :email, placeholder: "Email Address"%>
 	</div><div class="span4">
		<%= f.label :Password%>
		<%= f.password_field :password, placeholder: "Password" %>
 
		<%= f.label :Password_Confirmation%>
		<%= f.password_field :password_confirmation, placeholder: "Password Confirmation"%>
 
		<%= f.submit "Create my account"%>	
	</div> 	
	  <% end %>  
    </div> 
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %> 

<h1><%= @user.name %></h1>

<h2><%= @user.email %></h2>

Favorite restrooms, reviews, ratings, etc. 